---
title: "Testing"
output: html_notebook
---


```{r}
library(quantmod)
library(dplyr)
```

```{r}
getSymbols("SPY", src = "yahoo")

head(SPY)
tail(SPY)
# once it's loaded, exists("SPY") checks if data is already loaded
```

```{r}
library(data.table)
mydat <- fread('https://coinmetrics.io/data/eth.csv')
head(mydat)
```

```{r}
names(mydat) <- c("date", "volume", "txCount", "marketcap", "price", "exchangevolume", "generatedcoints", "fees", "ativeaddresses", "na")
head(mydat)

slim_dat <- mydat[,c(1,5)]
head(slim_dat)
```

```{r}

testdf <- as.data.frame(SPY)
setDT(testdf, keep.rownames = TRUE)[]
slim_stocks <- testdf[,c(1,7)]
# adjusted = column of closing prices adjusted for dividends and splits
head(slim_stocks)

slim_stocks <- slim_stocks %>% rename (date = rn)
```
```{r}
library(tidyverse)
(join <- left_join(slim_dat, slim_stocks))
```

```{r}
library(ggplot2)
library(plotly)
join <- drop_na(join)

join$date <- as.Date(join$date)

initial_buy_in <- 10000

# finding the portfolio values over time
join <- join %>%
  mutate(
    crypto_port_val = (initial_buy_in*price)/join$price[1],
    noncrypto_port_val = (initial_buy_in*SPY.Adjusted)/join$SPY.Adjusted[1]
         )
join
```

```{r}
g <- ggplot(data=join, aes(x = date)) +
  geom_line(aes(y = crypto_port_val), colour="blue") +
  geom_line(aes(y = noncrypto_port_val), colour = "grey") +
  ylab(label="Portfolio Value") +
  xlab("Date")

ggplotly(g)
```

